#ifndef __DARKNET_TA_1_H__
#define __DARKNET_TA_1_H__

#define TA_DRAKNET_TA_1_UUID {0xeff27aea, 0x8019, 0x8f98, { 0x49, 0x63, 0x40, 0x62, 0x33, 0xb5, 0x1e, 0x44 }}
#define TA_WRITE_TEE_FILE 0
#define TA_DELETE_TEE_FILE 1
#define TA_READ_TEE_FILE 2
#define TA_FILE_IS_EXIST 3
#define TA_VERIFICATION_WITHOUT_SPLIT 4
#define TA_VERIFICATION_WITH_SPLIT 5
#define TA_VERIFICATION_MATRIXA 6
#define TA_VERIFICATION_SPLIT1 7
#define TA_VERIFICATION_SPLIT2 8
#define TA_VERIFICATION_SPLIT3 9
#define TA_VERIFICATION_SPLIT4 10
#define TA_GENERATE_HA1 11
#define TA_GENERATE_HB1 12
#define TA_INIT_HASH_TABLE 13
#define TA_COPY_BUFFER 14
#define TA_PRE_CALCULATION 15
#define TA_VERIFY_BY_IFA 16
#define TA_VERIFY_DIFFRIENCE 17
#endif